development:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  timeout: 5000